import { Player, Quest, Season, QuestSelection, LeaderboardEntry } from '@/types';

export const mockSeason: Season = {
  id: '1',
  name: 'Spring 2026',
  start_date: '2026-03-01',
  end_date: '2026-05-31',
  is_active: true,
};

export const mockPlayers: Player[] = [
  {
    id: '1',
    name: 'Juan Martinez',
    nickname: 'Juancho',
    avatar_url: null,
    is_admin: true,
    first_quest_completed: true,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Maria Garcia',
    nickname: 'Mari',
    avatar_url: null,
    is_admin: false,
    first_quest_completed: true,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: '3',
    name: 'Carlos Lopez',
    nickname: 'Carlitos',
    avatar_url: null,
    is_admin: false,
    first_quest_completed: false,
    created_at: '2026-03-15T00:00:00Z',
  },
  {
    id: '4',
    name: 'Ana Rodriguez',
    nickname: 'Ani',
    avatar_url: null,
    is_admin: false,
    first_quest_completed: true,
    created_at: '2026-03-01T00:00:00Z',
  },
];

export const mockQuests: Quest[] = [
  {
    id: '1',
    title_es: 'El finde que... presentamos a alguien como quisimos',
    instructions_es: 'Uno de ustedes debe presentar al otro de la manera más creativa posible a un grupo de extraños. El presentador inventa un nombre, profesión, y una historia de fondo completamente falsa. El presentado debe seguir el juego durante toda la conversación. Bonus: si logran que los extraños les inviten a algo.',
    difficulty: 'medium',
    base_points: 25,
    mode: 'multiplayer',
    suggested_players: 2,
    default_point_split: { introducer: 10, introduced: 15 },
    status: 'active',
    season_id: '1',
    created_by: null,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: '2',
    title_es: 'El finde que... hablamos con acento todo la noche',
    instructions_es: 'Elige un acento (británico, italiano, mexicano, etc.) y mantenlo durante toda la noche en cualquier interacción social. No puedes romper el personaje ni explicar que es un juego. Si alguien te pregunta de dónde eres, debes inventar una historia coherente.',
    difficulty: 'easy',
    base_points: 10,
    mode: 'single',
    suggested_players: 1,
    default_point_split: null,
    status: 'active',
    season_id: '1',
    created_by: null,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: '3',
    title_es: 'El finde que... conseguimos el número de un extraño',
    instructions_es: 'Obtén el número de teléfono de alguien que no conoces usando una excusa completamente inventada (no romántica). Ejemplos: necesitas su número para una "encuesta importante", eres un "talent scout", o estás organizando un "evento exclusivo". Debes enviar un mensaje de prueba para verificar.',
    difficulty: 'medium',
    base_points: 25,
    mode: 'single',
    suggested_players: 1,
    default_point_split: null,
    status: 'active',
    season_id: '1',
    created_by: null,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: '4',
    title_es: 'El finde que... tomamos foto con un famoso de la calle',
    instructions_es: 'Consigue una foto con alguien que parezca famoso o que esté actuando como si lo fuera. Puede ser alguien que genuinamente reconozcas O alguien que simplemente tenga "aura de famoso". En el segundo caso, debes preguntarles "¿Eres [nombre inventado]?" y conseguir la foto de todas formas.',
    difficulty: 'hard',
    base_points: 50,
    mode: 'single',
    suggested_players: 1,
    default_point_split: null,
    status: 'active',
    season_id: '1',
    created_by: null,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: '5',
    title_es: 'El finde que... convencimos a alguien de una mentira absurda',
    instructions_es: 'Convence a un extraño de algo completamente falso y absurdo. Ejemplos: que eres un ex-astronauta, que Times Square se llama así por tu familia, que el edificio Empire State tiene un piso secreto solo para billonarios. Debes mantener la conversación por al menos 3 minutos sin que te descubran.',
    difficulty: 'medium',
    base_points: 25,
    mode: 'single',
    suggested_players: 1,
    default_point_split: null,
    status: 'active',
    season_id: '1',
    created_by: null,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: '6',
    title_es: 'El finde que... cantamos karaoke sin conocer la canción',
    instructions_es: 'Ve a un karaoke y elige una canción que nunca hayas escuchado. Debes cantarla con total confianza como si la conocieras de memoria. Puntos extra si el público se une o te aplaude.',
    difficulty: 'easy',
    base_points: 10,
    mode: 'single',
    suggested_players: 1,
    default_point_split: null,
    status: 'active',
    season_id: '1',
    created_by: null,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: '7',
    title_es: 'El finde que... intercambiamos personalidades por una hora',
    instructions_es: 'Dos jugadores intercambian personalidades completas por una hora en un lugar público. Deben imitar la forma de hablar, gestos, y opiniones del otro. Los demás amigos son los jueces de qué tan bien lo hacen.',
    difficulty: 'medium',
    base_points: 25,
    mode: 'multiplayer',
    suggested_players: 2,
    default_point_split: { player1: 12, player2: 13 },
    status: 'active',
    season_id: '1',
    created_by: null,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: '8',
    title_es: 'El finde que... dejamos que un extraño eligiera nuestra comida',
    instructions_es: 'Ve a un restaurante y pide a la persona de la mesa de al lado que elija tu comida completa (entrada, plato principal, bebida). Debes comer todo lo que elijan sin quejarte.',
    difficulty: 'easy',
    base_points: 10,
    mode: 'single',
    suggested_players: 1,
    default_point_split: null,
    status: 'active',
    season_id: '1',
    created_by: null,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: '9',
    title_es: 'El finde que... organizamos una cita a ciegas improvisada',
    instructions_es: 'Dos jugadores deben encontrar a dos extraños en un bar y convencerlos de tener una "cita doble improvisada" juntos. Los jugadores actúan como celestinos y deben lograr que los extraños intercambien números al final.',
    difficulty: 'hard',
    base_points: 50,
    mode: 'multiplayer',
    suggested_players: 2,
    default_point_split: { player1: 25, player2: 25 },
    status: 'active',
    season_id: '1',
    created_by: null,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: '10',
    title_es: 'El finde que... exploramos un barrio que nunca visitamos',
    instructions_es: 'Elige un barrio de NYC donde nunca hayas estado. Debes encontrar: 1) El mejor lugar para comer según un local, 2) Un "secreto" del barrio que solo los residentes conocen, 3) Una foto en el lugar más icónico del barrio.',
    difficulty: 'easy',
    base_points: 10,
    mode: 'single',
    suggested_players: 1,
    default_point_split: null,
    status: 'active',
    season_id: '1',
    created_by: null,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: '11',
    title_es: 'El finde que... fingimos ser turistas en nuestra propia ciudad',
    instructions_es: 'Pasa el día actuando como turista en NYC. Debes: pedir direcciones a lugares obvios, tomar fotos "típicas de turista", y preguntar recomendaciones a locales como si nunca hubieras estado aquí. Bonus si alguien te ofrece ayuda genuina.',
    difficulty: 'easy',
    base_points: 10,
    mode: 'single',
    suggested_players: 1,
    default_point_split: null,
    status: 'active',
    season_id: '1',
    created_by: null,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: '12',
    title_es: 'El finde que... completamos el desafío del subway',
    instructions_es: 'Toma una línea de subway de punta a punta. En cada parada donde el tren se detenga por más de 30 segundos, debes bajar, hacer algo memorable (foto, hablar con alguien, comprar algo), y volver a subir antes de que el tren se vaya.',
    difficulty: 'hard',
    base_points: 50,
    mode: 'single',
    suggested_players: 1,
    default_point_split: null,
    status: 'active',
    season_id: '1',
    created_by: null,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: '13',
    title_es: 'El finde que... hicimos de wingman/wingwoman profesional',
    instructions_es: 'Tu misión es ser el mejor wingman/wingwoman para otro jugador. Debes iniciar al menos 3 conversaciones con extraños para introducir a tu amigo/a de la manera más épica posible. El otro jugador evalúa tu desempeño.',
    difficulty: 'medium',
    base_points: 25,
    mode: 'multiplayer',
    suggested_players: 2,
    default_point_split: { wingperson: 15, target: 10 },
    status: 'active',
    season_id: '1',
    created_by: null,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: '14',
    title_es: 'El finde que... pedimos el especial secreto',
    instructions_es: 'Ve a 3 restaurantes o bares diferentes y en cada uno pregunta con total confianza por "el especial secreto" o "lo que no está en el menú". Debes documentar las reacciones y si efectivamente te dan algo especial.',
    difficulty: 'easy',
    base_points: 10,
    mode: 'single',
    suggested_players: 1,
    default_point_split: null,
    status: 'active',
    season_id: '1',
    created_by: null,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: '15',
    title_es: 'El finde que... creamos una historia colaborativa con extraños',
    instructions_es: 'Empieza una historia absurda con una frase y pide a 5 extraños diferentes que cada uno agregue una oración. Debes grabar o documentar la historia completa al final.',
    difficulty: 'medium',
    base_points: 25,
    mode: 'single',
    suggested_players: 1,
    default_point_split: null,
    status: 'active',
    season_id: '1',
    created_by: null,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: '16',
    title_es: 'El finde que... bailamos en un lugar inesperado',
    instructions_es: 'Pon música (con audífonos o bocina pequeña) y baila por al menos 1 minuto en un lugar público inesperado: lobby de edificio, fila del supermercado, andén del subway, etc. Debes lograr que al menos una persona se una o te aplauda.',
    difficulty: 'medium',
    base_points: 25,
    mode: 'single',
    suggested_players: 1,
    default_point_split: null,
    status: 'active',
    season_id: '1',
    created_by: null,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: '17',
    title_es: 'El finde que... hicimos un trade inesperado',
    instructions_es: 'Empieza con un objeto pequeño (clip, moneda, etc.) y haz trades con extraños hasta conseguir algo significativamente mejor. Documenta cada trade. El ganador es quien consiga el objeto de mayor valor.',
    difficulty: 'hard',
    base_points: 50,
    mode: 'multiplayer',
    suggested_players: 2,
    default_point_split: { winner: 35, participant: 15 },
    status: 'active',
    season_id: '1',
    created_by: null,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: '18',
    title_es: 'El finde que... dimos un tour falso',
    instructions_es: 'Actúa como guía turístico y da un tour de 10 minutos de algún lugar de NYC a turistas reales. Todo lo que digas debe ser inventado pero creíble. Bonus si te dan propina.',
    difficulty: 'hard',
    base_points: 50,
    mode: 'single',
    suggested_players: 1,
    default_point_split: null,
    status: 'active',
    season_id: '1',
    created_by: null,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: '19',
    title_es: 'El finde que... hicimos un picnic sorpresa',
    instructions_es: 'Organiza un picnic improvisado en Central Park e invita a al menos 2 extraños a unirse. Debes tener comida real para compartir y lograr que se queden al menos 15 minutos.',
    difficulty: 'medium',
    base_points: 25,
    mode: 'single',
    suggested_players: 1,
    default_point_split: null,
    status: 'active',
    season_id: '1',
    created_by: null,
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: '20',
    title_es: 'El finde que... completamos el desafío del cumplido',
    instructions_es: 'Da 10 cumplidos genuinos y específicos a 10 extraños diferentes durante la noche. No pueden ser cumplidos genéricos - deben ser observaciones reales sobre algo que la persona está haciendo, usando, o diciendo. Documenta las reacciones.',
    difficulty: 'easy',
    base_points: 10,
    mode: 'single',
    suggested_players: 1,
    default_point_split: null,
    status: 'active',
    season_id: '1',
    created_by: null,
    created_at: '2026-03-01T00:00:00Z',
  },
];

export const mockCurrentSelection: QuestSelection = {
  id: '1',
  quest_id: '1',
  season_id: '1',
  selected_at: '2026-04-02T20:00:00-04:00',
  opt_in_deadline: '2026-04-03T20:00:00-04:00',
  completion_deadline: '2026-04-05T18:00:00-04:00',
  status: 'accepting',
  quest: mockQuests[0],
};

export const mockLeaderboard: LeaderboardEntry[] = [
  { player: mockPlayers[1], total_points: 85, quests_completed: 4, rank: 1 },
  { player: mockPlayers[0], total_points: 60, quests_completed: 3, rank: 2 },
  { player: mockPlayers[3], total_points: 35, quests_completed: 2, rank: 3 },
];
